[package]
name = "ohm"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliproc = "2.0.0"
crayon = { git = "https://github.com/cdotrus/crayon", tag = "0.2.0" }
thiserror = "1.0"